# Generated by Django 5.1.4 on 2025-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='etherpad_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Etherpad ID'),
        ),
    ]
