# Generated by Django 5.1.4 on 2025-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomeeting',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videomeeting',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videomeeting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
