# Generated by Django 5.1.4 on 2025-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Изображение'),
        ),
    ]
