version: '3.5'

services:
  jitsi-web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: always
    ports:
      - "48843:443"  # Проброс порта Jitsi напрямую
    environment:
      ENABLE_AUTH: 1
      AUTH_TYPE: jwt
      JWT_APP_ID: my_jitsi_app
      JWT_APP_SECRET: my_jitsi_secret
    networks:
      - jitsi-network

networks:
  jitsi-network:
    driver: bridge