# Generated by Django 5.1.4 on 2025-01-05 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studygroup_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='access_requests',
            field=models.ManyToManyField(blank=True, related_name='group_access_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
