version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 StudyBuddy.asgi:application"
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/html:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge