version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 StudyBuddy.asgi:application"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/html:/var/www/html
      - static_data:/app/staticfiles
      - media_data:/app/media
    networks:
      - app-network

  etherpad:
    image: etherpad/etherpad:latest
    container_name: etherpad
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      - TITLE=StudyBuddy Etherpad
      - ADMIN_PASSWORD=s98dsf7gh9d87jg0s8d7fgh0987t87h98aft
      - TRUST_PROXY=true
      - DEFAULT_PAD_TEXT=Welcome to Etherpad!
    volumes:
      - etherpad-data:/opt/etherpad-lite/var
    networks:
      - app-network

volumes:
  etherpad-data:
  static_data:
  media_data:

networks:
  app-network:
    driver: bridge
