version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 StudyBuddy.asgi:application"
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - jitsi-web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/html:/var/www/html
    networks:
      - app-network

  jitsi-web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: always
    expose:
      - "80"
    environment:
      ENABLE_AUTH: 1
      AUTH_TYPE: jwt
      JWT_APP_ID: my_jitsi_app
      JWT_APP_SECRET: my_jitsi_secret
      PUBLIC_URL: https://meet.study.ilexx-tech.ru
      ENABLE_XMPP_WEBSOCKET: 1
      ENABLE_COLIBRI_WEBSOCKET: 1
      ENABLE_SCTP: 1
    networks:
      - app-network

  etherpad:
    image: etherpad/etherpad
    container_name: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./settings.json:/opt/etherpad-lite/settings.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge